<?php
/**
 * Created by PhpStorm.
 * User: Anonymou_Chen
 * Date: 2017/3/5
 * Time: 10:00
 */
namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends  Model{

    //指定表名
    protected  $table = 'student';

    //指定id
    protected  $primaryKey = 'id';

    //指定允许批量赋值的字段
    protected $fillable = ['name','age'];

    //不允许
    protected  $guarded = [];

    // 控制时间读入 自动维护时间戳
    public  $timestamps = true ;

    //
    protected  function  getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }


}
